### PR TITLE
Feature: support for multiple index types

### PR DESCRIPTION
**Pull request by jbarciauskas**
This enhancement provides a backwards-compatible way of supporting indexes that are sharded by logstash type as well as date.  On first page load, ElasticSearch is queried to get a list of indices that match the common logstash pattern, with an optional suffix in order to prevent pulling in non-log indexes (we use '-logs' as a suffix to the standard {@type}-{%YYYY.MM.DD} pattern). The Chosen javascript framework is used to support selection of multiple indexes.  Smart indexing is used to pare down the actual indexes queried.

### CODE REVIEW

**Comment by rashidkpc** [comment]
Hmm, not sure what might be going on, but this doesn't quite function for me. Initial request works, but I don't get an index selector and subsequent search/reset operations fail. This is on Firefox 14

That chosen plugin is pretty slick though. I might have to steal that for the field selection section.

**Comment by jbarciauskas** [comment]
What is the name of your logs index or indices? What is the output of Kibana/loader2.php?getindices=1

**Comment by rashidkpc** [comment]
Output of getindices was ["logstash"]

**Comment by jbarciauskas** [comment]
Were there any JavaScript errors? What does the subsequent call to
loader2.php look like and return? I created a test logstash index with one
event and it seemed to work but it was a limited test data set.

**Comment by rashidkpc** [comment]
Request => {"search":"","fields":[""],"offset":0,"timeframe":"15 minutes","graphmode":"count","index":null,"stamp":1345043134193}
Response => []

No errors. Maybe try to catch me on IRC today and we'll work through it?

**Comment by rashidkpc** [comment]
As we've retired the php version and the js has significantly diverged I'm going to close this, though do I like the idea of better type seperation in kibana

**Pull request closed without merging**
