### PR TITLE
Add Basic Auth via Sinatra

### PR DESCRIPTION
**Pull request by ShoeKSU**
Added Basic authentication from Sinatra FAQ:
http://www.sinatrarb.com/faq.html#auth

Code starts on line 44 of Kibana.rb:
use Rack::Auth::Basic, "Restircted Area" do |username, password|
  [username, password] == ['admin', 'admin']
end

### CODE REVIEW

**Comment by rashidkpc** [comment]
I'd like to do this, but make it configurable and disabled by default in KibanaConfig.rb

Some day I'd like a switchable backend to allow people to make multiple accounts and tie them to filters

**Comment by ShoeKSU** [comment]
I'd really like to see the backend setup as you describe.  I was looking for some sort of multi-user plugin for Sinatra, but noticed their basic-auth fit the minimum requirements I was looking for at the time.  

I'm working to get this tied to our LDAP infrastructure currently, not having much luck but haven't had much time with it either.  With the PHP version, it was easily accomplished via mod_auth_ldap and ssl directly with Apache, however, with Ruby, there seems to be a lot of options, but none that I have successfully implemented yet.  If I can tie it to LDAP, then I can limit it to specific groups of users, which is what I'd like to do.  I've tried to use Apache, but most of the passenger documentation/examples I've found deal mainly with Rails, which I'd like to avoid if all possible, just personal preference.  My next investigation is using the net-ldap option and seeing if I can find the right syntax for it.  

Any example documentation that you've seen doing any of this would be greatly appreciated.  

Thank you for your continued work on this project!

**Comment by ShoeKSU** [comment]
So not an hour after I replied, I have Kibana-Ruby working with Apache-Passenger with SSL and LDAP authentication.   

I'm still looking forward to the day when all the authentication is build directly into Kibana :)  Thanks.

**Comment by rashidkpc** [comment]
Awesome! Any interest in posting a sanitized example of your passenger/ldap setup here?

**Comment by ShoeKSU** [comment]
Well.. I can, but.  I ran into a couple issues with it.  I got it work on Ubuntu 12.04 with apache's built in libapache2-mod-passenger and Ruby 1.8.7, but I tried up upgrade to Ruby 1.9.2 and use the "passenger-install-apache2-module" installation instructions, and I'm getting errors.  Kibana Loads, but I'm getting some Internal 500 errors so i'm trying to tack down the issue.

If you want some Vanilla Instructions for Ruby1.87 and libapache2-mod-passenger, I can provide those if interested.

Also,  I seem to be having an issue with the Export with the Ruby Version.  Instead of actually prompting me to save a CSV, like the PHP version, its opening it directly in the browser without any delimiters, so just straight information.  I've confirmed it happens on both Ruby 1.8.7 and 1.9.3.  Any idea why this is happening?

**Comment by rashidkpc** [comment]
Just fixed the export thing, wasn't sending the headers. Gonna go ahead and close this for now.

**Comment by paradoxbound** [comment]
I would really interested in any sort of Kibana passenger guide as it is on the short list things my manager wants/needs for centralised logging.

**Comment by cdenneen** [comment]
I too would be interested in Kibana passenger guide

**Comment by ShoeKSU** [comment]
Sorry for the sloppiness of this.  It was taken from my notes over the last couple months and I haven't had time to clean it up yet.  I did cut out a few things since rashidkpc has made some updates, and included a config.ru so my own iteration is no longer necessary.  Hopefully this will get you pointed in the right direction.

Here is a pretty basic setup, that I use.  One thing to note is that I'm using Ubuntu 12.04 and the default Apache2 Package that comes with it.  With this, I am assuming you already have the OS and Basic Apache installed.  Also note, that I use the libapache2-mod-passenger package to handle the Passenger.  I do install the Gem but I could not make passenger work with Kibana using the provided instructions with the gem install.  if anyone can get it working, I'd love to see a good example.
1.  Install the base Packages needed to install and run Kibana solo (This installs Ruby 1.8.7):
   apt-get install git-core ruby rubygems libcurl4-gnutls-dev
2. Install Kibana as directed on the main page:  <br> https://github.com/rashidkpc/Kibana 

For the Lazy: 
Install: 
git clone --branch=kibana-ruby https://github.com/rashidkpc/Kibana.git 
cd Kibana 
gem install bundler 
bundle install 

Configure: 
Set your elasticsearch server in KibanaConfig.rb: 
Elasticsearch = "elasticsearch:9200" 
1. install the Passenger Gem: 
   gem install passenger
2.   install a few needed packages:
   apt-get install apache2-prefork-dev libapr1-dev libaprutil1-dev libapache2-mod-passenger

It usually enables by default, however, in case it does not:
a2enmod passenger
service apache2 restart  (or reload whichever you prefer)
1.  Passenger looks for a folder called "Public" in the program directory to serve the static images. Since Kibana uses the directory called "Static" to provide this, we need to make a symbolic link:
   ln -s /your/directory/Kibana/static /your/directory/Kibana/public
2.  Now just create a Virtual Host pointed at the public directory, example provided:
   &lt;VirtualHost *:80&gt;
   ServerName kibana.server.com
   DocumentRoot /your/directory/Kibana/public
   &lt;Directory /your/directory/Kibana/public&gt;
   Allow from all
   Options -MultiViews
   &lt;/Directory&gt;
   &lt;/VirtualHost&gt;

For me, this is all it took to get it up and running on Ubuntu 12.04.  I tested these instructions with a Kibana build pulled on Oct. 29, 2012.  I have yet to translate this to another Distribution.  I've been running in a test production environment with an Rsyslog/Logstash/Elasticsearch/Kibana setup for 3 months.   My supervisors have been very pleased with the results and I'm planning to move it into full production and replace our Splunk environment within the next Month.

**Comment by nicovpp** [comment]
When I use passenger with Kibana, I am not getting the pie chart on "terms" module by example. 

Did you manage to make all functionnalities working on your side ?

Standard functionnalities (research, historical chart...) are working fine for me

**Comment by ShoeKSU** [comment]
To be honest, I didn't know there was a Pie Chart on that module, and I just updated my copy to make sure I hadn't missed something.  So, if there is one, it must not be working.   I'm really only using it for Search/Research and Historical purposes.  Are you getting the Pie Chart when you run Kibana straight as a Sinatra App, by running it as "ruby kibana.rb"?  If so, then I guess Passenger must be missing some functionality there.

**Comment by nicovpp** [comment]
Yes all functionnalities are working when I launch Kibana as a Sinatra app (and the pie chart).
I was trying to use passenger in order to use ldap authentication but it seems that I will have tu use basic authentication with a single user/password.
Thanks for your answer (and if someone manages to make everything run with passenger I am still interested...)

**Pull request closed without merging**
