### PR TITLE
Refactored file structure to allow app to be mounted into a Rails application

### PR DESCRIPTION
**Pull request by fabn**
As I told you in #106 I need to mount your application inside a bigger Rails project (with devise authentication). 

I've refactored some code and moved the applications code into a `KibanaApp` class. Application is the same, and the existing specs are passing. Further, `ruby kibana.rb` from top level directory still works, since I've put the app call in that file.

I've used this fork in a rails app with these lines

``` ruby
# In Gemfile
gem 'kibana', :git => 'git://github.com/fabn/Kibana.git', :branch => 'sinatra-app'

# In routes.rb, this allows access to kibana only for devise authenticated users
authenticate(:user) do
  mount KibanaApp, at: 'logs'
end
```

### CODE REVIEW

**Comment by josegonzalez** [comment]
Is this mergeable?

**Comment by fabn** [comment]
It was when I wrote it, however it has a problem with assets serving when mounted in path differents than /. Since I got no feedback on this I haven't investigated on it.

I think it needs a helper for assets inclusion to be used in html templates, resque server do that in this way:
- [template code](https://github.com/defunkt/resque/blob/master/lib/resque/server/views/layout.erb#L6-L10)
- [helper function](https://github.com/defunkt/resque/blob/master/lib/resque/server.rb#L37-L40)

Or one can use sprockets, but I don't know how to use it in a rack application.

**Comment by jamtur01** [comment]
Just use sinatra-static-assets.

**Comment by fabn** [comment]
@jamtur01 thanks for the hint, I'll look at that.

**Comment by jamtur01** [comment]
@fabn I rebased this and fixed some minor issues - https://github.com/rashidkpc/Kibana/pull/246

**Comment by fabn** [comment]
Awesome thanks for that.

**Pull request closed without merging**
