### PR TITLE
Move Kibana's sinatra bits into a Sinatra::Base class

### PR DESCRIPTION
**Pull request by jordansissel**
for easier launching from things other than the command line (like embedded into
logstash releases).

The new kibana.rb now exists to parse flags and run the app.
No visible functionality should have changed.

### CODE REVIEW

**Comment by jordansissel** [comment]
I also verified that kibana works well using the threaded webserver logstash ships with (ftw)

**Comment by jordansissel** [comment]
Don't merge this yet, I'm still testing to make sure it works in logstash

**Comment by jordansissel** [comment]
Don't merge this yet, I'm still testing to make sure it works in logstash

**Comment by josegonzalez** [comment]
Is this mergeable?

**Pull request merged**
