### PR TITLE
Implement splunk like pipe ("|") mechanism so we can use search bar for ...

### PR DESCRIPTION
**Pull request by r-duran**
...score, trend etc.

sample:

@source_host:firewall AND srcip:192.168.7.44 AND dstport:22 | score dstip

### CODE REVIEW

**Comment by rashidkpc** [comment]
I like this, haven't had time to test. One concern is that it seems like it would break on searches for events that contain a | character

**Comment by awheeler** [comment]
I'd very much like to see this incorporated, and extended to support multiple fields:
@source_host:nginx AND response:404 | score clienthost request

This example would give us an analysis of page not found requests by host and the actual failed request.
I'll take a stab at this myself, though I'm not very familiar with Ruby.
The events with a | char can be addressed by skipping | inside of quotes -- I'll work on that too.

**Comment by r-duran** [comment]
Well in splunk if you want to search for pipe char, it needs to be in a quoted search string like 'hostname:"foo|bar" AND scrip:192.168.7.44'

I will implement it when I have time. If nobody volunteer to do it.

**Comment by awheeler** [comment]
I've implemented that by assuming that there will never be a ' or " after the real pipe char:

```
var pattern=/^(.*)\|([^"']*)$/;
  if (pattern.test(window.hashjson.search) == true) {
    var results = window.hashjson.search.match(pattern);
    var search = $.trim(results[1]);
    var fields = results[2].split(' ');
    var field = fields.slice(2).join(',,');
    var mode = fields[1];
```

Also got multi-field working by joining the multiple fields with ',,'.  But still need to fix the search and analyze buttons on the results.
I had to manually apply your changes r-duran, as the code that I checked out didn't match your diffs.

**Comment by r-duran** [comment]
@awheeler 
I didn't  try it yet but it seems good to me, nice work.

@rashidkpc 
Kibana has great potential as a splunk like interface but it lacks features that graylog2 has like user management, saved streams and alarms. But graylog2 lacks elegant and functional interface that kibana has. It is pain to search by fields in graylog2. I wish you could join your forces.

It seems I will start to implement kibana features in graylog2 because the opposite is too much work.

Thanks for your inspiring works.

**Comment by awheeler** [comment]
@r-duran
Are the graylog2 maintainers receptive to Kibana/Splunk-like features?
I found Kibana through Graylog2, but when I couldn't see how to graph the results of a search on a timeline, I stopped considering it and then bumped across Kibana, which seemed to be much closer to what I was looking for (a Splunk replacement) -- with just the changes I'm making, I can do 80% of what I was doing with Splunk.
It would be very cool to migrate the Kibana front-end/features into Graylog2.

**Comment by r-duran** [comment]
@awheeler 
I didn't discussed this with them yet. But I'm sure they will also want such UI functionality.

Graylog2 is more than a UI for elasticsearch. It is more close to splunk feature wise than kibana but it looses in UI side. The problem is graylog2 has two different mechanism for searching and analyzing. It has quickfilter search which you need to fill multiple textboxes for your search, more of them if you want to search on fields. And it has ajax based  cli-like analytics component that has very ugly syntax, and uglier results representation compared to kibana's score, trend, stats mechanism.

**Comment by awheeler** [comment]
Now supports both score and trend, and the sub-search buttons work.  Pull request sent.

**Comment by rashidkpc** [comment]
Appreciate the feedback from both of your guys. I went ahead and merged awheeler's pull request and pushed it out to the demo site. Thanks again to both of you :-D

**Pull request closed without merging**
