### PR TITLE
Written a basic multi-user access system

### PR DESCRIPTION
**Pull request by MikeWorth**
I've found some code in commit 4052967 for requiring a username and
password for access and ressurected it with some changes to allow
multiple users to have access to different subsets of the logs.
Each user has their own filter string which is used to configure
their access in the users.php file.

### CODE REVIEW

**Comment by MikeWorth** [comment]
Please also note that this work was completed while working for Oxford University IT services for the purpose of crediting

**Comment by rashidkpc** [comment]
I like where this is going!

**Comment by MikeWorth** [comment]
Unfortunately, today is the last day of my internship working on this, hopefully all the changes I've made to date are useful. As much as I won't be working full time on this, feel free to contact me if you need my help understanding what was going on in my mind at any point or you have any other questions.

There is a good chance that someone at Oxford University IT Services will take the preliminary work I've done and put a full centralised log system into production, this may well include Kibana. If this is the case, it is likely that you will see more code appear in the ox-it/kibana repository.

Thanks,
Mike

**Comment by rashidkpc** [comment]
As the php version has been retired I'm closing this. If you're still interested there is currently a fork of kibana-ruby that is implementing a flexible auth system, thanks!

**Pull request closed without merging**
