### PR TITLE
Conform to Rack conventions: Rename /static dir to /public. Add /tmp dir...

### PR DESCRIPTION
**Pull request by Yggdrasil**
Hi, to make Kibana easier to deploy under the popular Passenger application server only a few simple changes were needed, since Kibana already uses the Rack interface.

Passenger assumes that Rack application directories have a certain simple layout. See: http://www.modrails.com/documentation/Users%20guide%20Nginx.html#deploying_a_rack_app

I basically renamed /static to /public, created a /tmp dir, and made one change to kibana.rb. I have this setup running nicely on my nginx+passenger server.

Passenger is quite a popular way to deploy Ruby apps, so this change could benefit many people who already have an Apache or Nginx server running and would like to avoid running yet another Ruby webserver.

Would you please consider merging this into your mainline repo?

Regards, Martijn Heemels

### CODE REVIEW

**Comment by rashidkpc** [comment]
Agree this is important. I'll be merging this in the next few days. Thanks!

**Comment by Yggdrasil** [comment]
Thanks!

**Comment by Yggdrasil** [comment]
Hi rashidkpc, could you have a look at merging this before things grow too far apart? Would be much appreciated. Thanks!

**Comment by josegonzalez** [comment]
@rashidkpc <3

**Comment by rashidkpc** [comment]
Done and done. Thanks!

**Pull request closed without merging**
